Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -4,6 +4,20 @@ on:
 jobs:
   build:
     runs-on: ubuntu-latest
+    #Service rajouté séance 8
+    services:
+      nginx:
+        image: nginx:latest
+        ports:
+          - 80:80
+        volumes:
+          - ./Prototypes/POC-Prototype1/dist:/usr/share/nginx/html:ro
+        options: >
+          --health-cmd="curl -f http://localhost || exit 1"
+          --health-interval=5s
+          --health-timeout=3s
+          --health-retries=10
+
     steps:
       - name: Download sources
         uses: actions/checkout@v5
@@ -25,10 +39,10 @@ jobs:
         run: |
           cd Prototypes/POC-Prototype1
           npm run build
-      - name: Start frontend
-        run: |
-          cd Prototypes/POC-Prototype1
-          docker compose up --detach
+      #- name: Start frontend
+      #  run: |
+      #    cd Prototypes/POC-Prototype1
+      #    docker compose up --detach
       - name: Install GreenIT Analysis CLI
         run: |
           wget https://github.com/cnumr/GreenIT-Analysis-cli/archive/refs/heads/master.zip
@@ -36,10 +50,25 @@ jobs:
           cd GreenIT-Analysis-cli-master
           npm install
           npm link
+      #- name: Wait for frontend
+      #  uses: docker://benel/wait-for-response:1
+      #  with:
+      #    args: http://localhost/ 200 30000 500
+
+      #rajouté séance 8
       - name: Wait for frontend
-        uses: docker://benel/wait-for-response:1
-        with:
-          args: http://localhost/ 200 30000 500
+        run: |
+          for i in {1..30}; do
+            if curl -s http://localhost >/dev/null; then
+              echo "Frontend is up!"
+              exit 0
+            fi
+            echo "Waiting for frontend..."
+            sleep 1
+          done
+          echo "Frontend failed to start"
+          exit 1
+
       - name: Run GreenIT Analysis CLI
         run: |
           cd Prototypes/POC-Prototype1
